name: kopi_verse
description: "Coffee Shop App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  http: ^1.2.2
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.6
  provider: ^6.1.2
  barcode: ^2.2.8
  flutter_svg: ^2.0.16
  file_picker: ^8.1.6
  http_parser: ^4.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
